#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------
# 30-build-gasket-deb.sh
#
# Build a Debian package (gasket-dkms_*.deb) for the Coral driver
# against the CURRENT running kernel, and store the result in:
#
#   ${ROOT_DIR}/artifacts/gasket-dkms_<kernel>.deb
#
# This script:
#   1. Requires a valid gasket-driver checkout at:
#        ${ROOT_DIR}/artifacts/gasket-driver
#      (created/updated by 20-fetch-gasket.sh).
#   2. Applies local compatibility patches (no_llseek and the Linux 6.13+
#      MODULE_IMPORT_NS API change) if they are not already present.
#   3. Runs `debuild` in the gasket-driver directory:
#        debuild -us -uc -tc -b -d
#   4. Locates the newest gasket-dkms_*.deb generated by debuild.
#   5. Copies that .deb into:
#        ${ROOT_DIR}/artifacts/gasket-dkms_${KVER}.deb
#      where KVER is the current `uname -r`.
#
# Notes:
#   - This script assumes relevant build dependencies are already
#     installed (00-bootstrap-env.sh).
#   - It builds for the *current* kernel; if you boot into a different
#     SCALE BE/kernel, re-run this to get a matching .deb.
#
# To CLEAN UP / UNDO:
#
#   - Remove built packages:
#       rm -f ${ROOT_DIR}/artifacts/gasket-dkms_*.deb
#
#   - If you also want to discard the source tree and any build
#     artifacts under it:
#       rm -rf ${ROOT_DIR}/artifacts/gasket-driver
#
#   - This script does not install anything system-wide; it only
#     compiles and copies .deb files into your artifacts directory.
# ---------------------------------------------------------------------

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ARTIFACT_DIR="${ROOT_DIR}/artifacts"
GASKET_DIR="${ARTIFACT_DIR}/gasket-driver"
PATCH_DIR="${ROOT_DIR}/patches"
NO_LLSEEK_PATCH="${PATCH_DIR}/gasket-no_llseek-truenas-6.12.patch"
MODULE_IMPORT_NS_PATCH="${PATCH_DIR}/gasket-module-import-ns-linux-6.13.patch"
KVER="$(uname -r)"

echo "==> [30-build-gasket-deb] Repo root: ${ROOT_DIR}"
echo "==> Kernel: ${KVER}"
echo "==> Gasket dir: ${GASKET_DIR}"
echo "==> Artifact dir: ${ARTIFACT_DIR}"
echo "==> Patch dir: ${PATCH_DIR}"

# Ensure the gasket-driver source tree exists
if [ ! -d "${GASKET_DIR}" ]; then
  echo "ERROR: ${GASKET_DIR} does not exist. Run 20-fetch-gasket.sh first."
  exit 1
fi

# Ensure patches dir exists (so we have a standard layout)
if [ ! -d "${PATCH_DIR}" ]; then
  echo "ERROR: Patch directory ${PATCH_DIR} does not exist."
  echo "       Expected to find compatibility patches"
  exit 1
fi

# ---------------------------------------------------------------------
# Apply no_llseek compatibility patch (idempotent)
# ---------------------------------------------------------------------
GASKET_CORE="${GASKET_DIR}/src/gasket_core.c"

if [ ! -f "${GASKET_CORE}" ]; then
  echo "ERROR: ${GASKET_CORE} not found. Is the gasket-driver source layout as expected?"
  exit 1
fi

if grep -q 'no_llseek noop_llseek' "${GASKET_CORE}"; then
  echo "==> no_llseek compatibility already present in src/gasket_core.c (skipping patch)"
else
  if [ ! -f "${NO_LLSEEK_PATCH}" ]; then
    echo "ERROR: Expected patch file not found: ${NO_LLSEEK_PATCH}"
    echo "       Cannot apply no_llseek compatibility patch."
    exit 1
  fi
  echo "==> Applying no_llseek compatibility patch to src/gasket_core.c"
  (
    cd "${GASKET_DIR}"
    # Patch uses paths like a/src/gasket_core.c, so -p1 is appropriate
    patch -p1 < "${NO_LLSEEK_PATCH}"
  )
fi

# Linux 6.13 changed MODULE_IMPORT_NS() to accept string literals. Apply a
# version-gated source change so this package remains buildable on both the
# Linux 6.12 kernel in TrueNAS 25.x and Linux 6.18 in TrueNAS 26.x.
GASKET_PAGE_TABLE="${GASKET_DIR}/src/gasket_page_table.c"

if grep -q 'MODULE_IMPORT_NS("DMA_BUF")' "${GASKET_PAGE_TABLE}"; then
  echo "==> MODULE_IMPORT_NS compatibility already present (skipping patch)"
else
  if [ ! -f "${MODULE_IMPORT_NS_PATCH}" ]; then
    echo "ERROR: Expected patch file not found: ${MODULE_IMPORT_NS_PATCH}"
    exit 1
  fi
  echo "==> Applying Linux 6.13+ MODULE_IMPORT_NS compatibility patch"
  (
    cd "${GASKET_DIR}"
    patch -p1 < "${MODULE_IMPORT_NS_PATCH}"
  )
fi

# ---------------------------------------------------------------------
# Inject a local override to skip dh_md5sums (TrueNAS sudo/sh weirdness)
# ---------------------------------------------------------------------
RULES_FILE="${GASKET_DIR}/debian/rules"

if [ ! -f "${RULES_FILE}" ]; then
  echo "ERROR: debian/rules not found in ${GASKET_DIR}"
  exit 1
fi

if ! grep -q 'override_dh_md5sums' "${RULES_FILE}"; then
  echo "==> Injecting override_dh_md5sums into debian/rules"
  {
    echo
    echo "override_dh_md5sums:"
    # Use printf to ensure a literal tab (Makefile requirement)
    printf '\t@echo "Skipping dh_md5sums on TrueNAS (sudo/sh mismatch workaround)"\n'
  } >> "${RULES_FILE}"
else
  echo "==> override_dh_md5sums already present in debian/rules (not touching it)"
fi

# ---------------------------------------------------------------------
# Build the gasket-dkms .deb
# ---------------------------------------------------------------------
cd "${GASKET_DIR}"

echo "==> Building gasket-dkms .deb via debuild"
# -us/-uc: do not sign source or changes
# -tc: clean tree before/after
# -b: binary-only build
# -d: skip build-dependency checks (we handle deps elsewhere)
debuild -us -uc -tc -b -d

cd "${ARTIFACT_DIR}"

# Grab the most recent Debian-built gasket-dkms_*_all.deb
DEB_FILE="$(ls -1 gasket-dkms_*_all.deb 2>/dev/null | sort | tail -n 1 || true)"

if [ -z "${DEB_FILE}" ]; then
  echo "ERROR: No gasket-dkms_*.deb found after build."
  exit 1
fi

DEST_FILE="${ARTIFACT_DIR}/gasket-dkms_${KVER}.deb"

echo "==> Copying ${DEB_FILE} to ${DEST_FILE}"
cp -f "${DEB_FILE}" "${DEST_FILE}"

echo "==> [30-build-gasket-deb] Done. Built: ${DEST_FILE}"
